### ISSUE TITLE
Issue and some question (auto search)

### ISSUE THREAD

**Issue by ghost** [airdcpp-web/airdcpp-extension-js#1]
Hi
I tested the auto search extension but when I run it I have to have it active in a linux terminal window. Is there any way i can get it to work like the other extension?

Do you plan to get more extensions? 
Or build in auto search? 

And can you help me where to learn som programing so i can try my self even if i gone fail ;).

**Comment by maksis** [comment]
> Is there any way i can get it to work like the other extension?

Not directly. A new standalone extension could be written based on https://github.com/airdcpp-web/airdcpp-create-extension though.

> Do you plan to get more extensions?
> Or build in auto search?

I'm most likely going to write new extensions, but only for features that I also need myself (which won't include auto search or other examples listed here)

> And can you help me where to learn som programing so i can try my self even if i gone fail ;).

Hmm, I'm not sure where to start from if you haven't done any programming before, but Javascript tutorials might be the most helpful ones if you are planning to write extensions. 

When writing actual  extensions, https://github.com/airdcpp-web/airdcpp-create-extension is probably the place to look at.
